### ISSUE TITLE
[Feature]: Replace the reachable with an injected function

### ISSUE THREAD

**Issue by markcty** [xline-kv/Xline#143]
### Description about the feature

Replace the reachable with an injected function. Currently, we use an atomic bool to control whether the server is reachable. We can extend the logic to a function that could help us test in other ways.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Can we close this issue when we merge pr #288? @bsbds

**Comment by bsbds** [comment]
> Can we close this issue when we merge pr #288? @bsbds

This will be closed in #316
