### ISSUE TITLE
Use a unique propose id

### ISSUE THREAD

**Issue by themanforfree** [xline-kv/Xline#219]
Currently our propose id is randomly generated using `uuid` crate like this:
```Rust
/// Generate propose id
fn generate_propose_id(&self) -> ProposeId {
    ProposeId::new(format!("{}-{}", self.name, Uuid::new_v4()))
}
```
 but this method may still randomly generate the same propose id, so we need a new method to generate propose id, a possible solution is to directly use the `IdGenerator` we used in the lease module to generate a globally incremented unique id

**Comment by themanforfree** [comment]
> Seems that 256 available propose id per millisecond is not enough.

Can you provide more details?

**Comment by qstommyshu** [comment]
Hi, has this issue been fixed? I can't find the function in my recent cloned repo.
```Rust
/// Generate propose id
fn generate_propose_id(&self) -> ProposeId {
    ProposeId::new(format!("{}-{}", self.name, Uuid::new_v4()))
}
```

**Comment by iGxnon** [comment]
Should be closed after RIFL implemented

**Comment by EshaanAgg** [comment]
@iGxnon Is this issue open for contribution?

**Comment by iGxnon** [comment]
> ? I would like to take a short a

Sorry, we will fix this issue later with other mechanisms.

**Comment by EshaanAgg** [comment]
Okay! Thanks for the reply!
