### ISSUE TITLE
[Bug]: Watch prev_kv

### ISSUE THREAD

**Issue by themanforfree** [xline-kv/Xline#277]
### Description about the feature

In the current implementation, we have not handled the `prev_kv` flag in the `WatchCreateRequest`, all watch events need to read  previous `KeyValue`  from storage, This behavior is incorrect and can lead to unnecessary I/O operations.

The correct method is to minimize I/O operations by only reading previous `KeyValue` when it is required by the current watcher.

The following diagram is the events path after handling `prev_kv` flag:

![image](https://github.com/datenlord/Xline/assets/56149350/971cbbd1-1d5e-40d4-a75f-0056a1ba931a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liangyuanpeng** [comment]
> This behavior is incorrect and can lead to unnecessary I/O operations.

So this is a bug and not feature? because your title prefix with [feature].

**Comment by themanforfree** [comment]
> > This behavior is incorrect and can lead to unnecessary I/O operations.
> 
> So this is a bug and not feature? because your title prefix with [feature].

Here is to add the logic that was not handled before, so I used the feature, but it would be better to mark it as a bug
