### ISSUE TITLE
[Bug]: Lease grant request handling in Xline server

### ISSUE THREAD

**Issue by bsbds** [xline-kv/Xline#329]
### Description about the bug

In Xline server, the lease id is generated in `xline/src/server/lease_server.rs`, then it mutates the original request. 
```rust
    async fn lease_grant(
        &self,
        mut request: tonic::Request<LeaseGrantRequest>,
    ) -> Result<tonic::Response<LeaseGrantResponse>, tonic::Status> {
        debug!("Receive LeaseGrantRequest {:?}", request);
        let lease_grant_req = request.get_mut();
        if lease_grant_req.id == 0 {
            lease_grant_req.id = self.id_gen.next();
        }
        ...
    }
```
If we directly propose lease grant request to CURP from the outside client, the lease id will not be generated. So we need a way to generate the lease id in the CURP executor.

The same for lease grant in `xline/src/server/lock_server.rs`.

### Version

0.4.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bsbds** [comment]
Is it possible we could add a function to the command that update the lease id of itself and call it before `handle_propose`
https://github.com/datenlord/Xline/blob/f382030b2798711d13d8033c6a2d5a0f33824ca9/curp/src/server/curp_node.rs#L112-L117

**Comment by themanforfree** [comment]
every node in the cluster will handle propose of the same request, if we update lease id at here, we cannot guarantee that the lease id of all nodes is the same, so we must determine the lease id before client sending a propose.

A possible solution is, outside client generates a lease ID and send the propose, the curp server determines whether the lease ID is being used. If the lease ID has been used, curp
 server will return an error, than client will generate a new lease ID and resend the propose.

**Comment by bsbds** [comment]
Lease id generation will be implemented in the outside client, using the following strategy:
```
| prefix       | suffix  |
| 7 bytes      | 1 byte  |
| random bytes | cnt     |
```

The prefix bytes will generated from system random number source and it's very unlikely that an collision will occur.
