### ISSUE TITLE
Improve the readability of boot up errors in Xline

### ISSUE THREAD

**Issue by Phoenix500526** [xline-kv/Xline#330]
At present, there are two ways to boot up an Xline instance: using command-line arguments or a configuration file. Typically, when no cmd line arguments are provided, the configuration information is read from `/etc/xline_server.conf`. However, if this file doesn't exist, it will throw out an error message, "Error: No such file or directory (os error 2)", which lacks readability. We can improve its readability by adding the configuration file name in this error message.

**Comment by MarkGaox** [comment]
Hi, can you assign this to me?

**Comment by Phoenix500526** [comment]
@MarkGaox Sure, thank you for your contribution.
