### ISSUE TITLE
[Bug]: `leader_retires` read compacted log entry

### ISSUE THREAD

**Issue by themanforfree** [xline-kv/Xline#331]
### Description about the bug

When the leader needs to be demoted to follower, will call the `leader_retires` method.
```rust
fn leader_retires(&self) {
    debug!("leader {} retires", self.id());

    // when a leader retires, it should wipe up speculatively executed cmds by resetting and re-executing
    let _ig = self.ctx.cmd_tx.send_reset(None);

    let mut cb_w = self.ctx.cb.write();
    cb_w.clear();

    let log_r = self.log.read();
    for i in 1..=log_r.commit_index {
        let entry = log_r.get(i).unwrap_or_else(|| {
            unreachable!(
                "system corrupted, apply log[{i}] when we only have {} log entries",
                log_r.last_log_index()
            )
        });
        self.ctx.cmd_tx.send_after_sync(Arc::clone(&entry.cmd), i);
    }
}
```
and this method will get all log entries before commit index, however, old entries may not be available after we implement log compact.

### Version

0.4.1 (Default)

### Relevant log output

```shell
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: system corrupted, apply log[1] when we only have 132758 log entries', /home/guanyu/Xline/curp/src/server/raw_curp/mod.rs:998:17
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themanforfree** [comment]
Why re-execute all commands in the original design? Is it possible to keep part of the data in the state machine and wait for new leader append entries? @markcty

**Comment by markcty** [comment]
Because old leader might have speculatively executed un-synced commands. These commands could get lost after the new leader is established. But since the old leader have already executed these commands with its state changed. We must recover to previous state. The easiest way, which is adopted now, is to re-execute all commands. Possible optimization would be to recover from the previous snapshot or to invent some roll-back mechanism.

**Comment by themanforfree** [comment]
> It's because old leader might have speculatively executed un-synced commands. These commands could get lost after the new leader is established(see the Curp paper for details). So the old leader must revert to previous state when these commands have not been executed. The easiest way, which is adopted now, is to re-execute all commands. Possible optimization would be to recover from the previous snapshot or to invent some roll-back mechanism.

Speculatively executed does not change the state of CE, why do we need to reset the entire CE in this case

**Comment by markcty** [comment]
> > It's because old leader might have speculatively executed un-synced commands. These commands could get lost after the new leader is established(see the Curp paper for details). So the old leader must revert to previous state when these commands have not been executed. The easiest way, which is adopted now, is to re-execute all commands. Possible optimization would be to recover from the previous snapshot or to invent some roll-back mechanism.
> 
> Speculatively executed does not change the state of CE, why do we need to reset the entire CE in this case. @markcty

If `sp_exe` doesn't change the state, then I think it's ok. I guess I hadn't got to know the implementation when I was writing this part.
