### ISSUE TITLE
[Refactor] Execution error types

### ISSUE THREAD

**Issue by bsbds** [xline-kv/Xline#397]
## Background
In xline storage, we use `ExecuteError` to represent various error types when executing the command.
The current implementation is like this
```rust
/// Error met when executing commands
#[derive(Error, Debug, Clone)]
pub enum ExecuteError {
    /// Kv error
    #[error("kv error: {0}")]
    KvError(String),
    /// Lease error
    #[error("lease error: {0}")]
    LeaseError(String),
    /// Auth error
    #[error("auth error: {0}")]
    AuthError(String),
    /// Db error
    #[error("db error: {0}")]
    DbError(String),
    /// Permission denied
    #[error("permission denied")]
    PermissionDenied,
}

impl ExecuteError {
    /// Key not found
    pub(crate) fn key_not_found() -> Self {
        Self::KvError("key not found".to_owned())
    }

    /// Lease not found
    pub(crate) fn lease_not_found(lease_id: i64) -> Self {
        Self::LeaseError(format!("lease {lease_id} not found"))
    }

    ...
}
```

and in `cmd_worker` we map the error to a string and return it to the client.
```rust
                    ce.execute(cmd.as_ref(), index)
                        .await
                        .map_err(|e| e.to_string())
 ```

This type of error handling is sufficient in server only implementation. However, as we introduced the outside client, we cannot recognize the specific error unless we match the entire error string. Thus it will be much more convenient to have distinct error types of execution result.

### Step 1
We could refactor the `ExecuteError` to more fine grained error typs like:
```rust
pub enum ExecuteError {
    InvalidRequest(String),
    KeyNotFound,
    ...
}
```
### Step 2

Currently the error type is associated to the `CommandExecutor` trait, I suggest to move it to the `Command` trait. As we need to specific the generic in `curp`, it's not nice to always have two generics.
```rust
#[async_trait]
pub trait CommandExecutor<C>: Sync + Send + std::fmt::Debug
where
    C: Command,
{
    /// Error type
    type Error: std::fmt::Debug + Send + Sync + Clone + std::error::Error;
    
    ...
```

### Step 3

Then we just need to refactor the relevant code in `curp` to include the execution error type as part of the `ProposeError`
```rust
pub enum ProposeError<C: Command> {
    ExecutionError(C::Error),
    ...
}
 ```

**Comment by Phoenix500526** [comment]
Resolved in pr #399
