### ISSUE TITLE
[Refactor] etcd error compatibility

### ISSUE THREAD

**Issue by bsbds** [xline-kv/Xline#415]
In etcd, the errors between server and client are passed through GRPC status. The client get the error types by parsing the error string in server responses. See https://github.com/etcd-io/etcd/blob/main/api/v3rpc/rpctypes/error.go.

Xline's server error types does not compatible with etcd's because it uses diffrerent grpc status string.

The Xline servers(https://github.com/xline-kv/Xline/tree/master/xline/src/server) are basically a compatible layer for etcd client. It convert the `ExecuteError` to GRPC status. 

In order to make etcd client be able to recognize Xline's server errors, I plan to add a `EtcdError` enum to Xline which is exactly the same as in etcd server errors. And construct a mapping from `ExecuteError` to `EtcdError`. Whenever we got an `ExecuteError` in Xline servers, we firstly convert it to a `EtcdError`, and then convert that `EtcdError` to GRPC status that will be returned to etcd client.

**Comment by Phoenix500526** [comment]
Please add more details about your design.

**Comment by bsbds** [comment]
For errors returned to etcd client, we have two type of error during the execution stage.
one is the `ValidationError`
https://github.com/xline-kv/Xline/blob/d37bc50dd8ffd4d126e74ba8e3cc02134ec1cee6/xline/src/request_validation.rs#L187-L190
and the other is `ExecuteError`
https://github.com/xline-kv/Xline/blob/d37bc50dd8ffd4d126e74ba8e3cc02134ec1cee6/xline/src/storage/execute_error.rs#L4-L10

We build mapping for each of these error types to `EtcdError`, and ultimately convert `EtcdError` to GRPC status, so this make sure that all errors returned to etcd client contains valid GRPC error string.

![20230818_11h38m45s_grim](https://github.com/xline-kv/Xline/assets/69835502/346e83a5-a524-4d44-94d3-c81a283b12aa)

Note that for some error types that exist in Xline but does not exist in etcd, we just returned a specific GRPC status code to the client.

**Comment by iGxnon** [comment]
LGTM

**Comment by Phoenix500526** [comment]
Can the `ValidationError` and `ExecuteError` convert to `tonic::Status` directly?  What are the relationships between `EtcdError` and `ClientError::EtcdError`?

**Comment by themanforfree** [comment]
LGTM
