### ISSUE TITLE
[Refactor]: sp and ucp recovery

### ISSUE THREAD

**Issue by themanforfree** [xline-kv/Xline#417]
## Context
SP: Temporarily preserving the command for conflict detection.
UCP: Temporarily preserving the command for conflict detection. but only for leader, including commands that can not be inserted into the `sp` due to conflicts.

recover of ucp:
```rust
...
  if is_leader {
      // all uncommitted cmds should stay in ucp until they are executed
      raw_curp.ctx.ucp.map_lock(|mut ucp_l| {
          for e in &entries {
              if let EntryData::Command(ref cmd) = e.entry_data {
                  let _ig = ucp_l.insert(e.id().clone(), Arc::clone(cmd));
              }
          }
      });
  }
...
```

## Problom
1. During cluster recovery, it is possible that a new leader might be elected, and this new leader can not restore `ucp` from the logs.
2. During the recovery process, all persistent logs are inserted into `ucp`. This will result in the insertion of a lot of useless content.
3. Assuming the successful completion of `fast_round` for `cmd1`. The leader executed `cmd1` and wrote the log, yet synchronization has not commenced. If the cluster restart at this time, sp will be lost. And the old leader will have an extra log entry,  and `cmd1` has successfully provided a response to the client.

## Solution and discuss

The additional part in `ucp` must be conflict with `sp`. So the `fast_path` is certainly unsuccessful. If the command hasn't been removed from UCP, then it certainly hasn't been `after_synced`, so the `slow_path` is certainly unsuccessful too. This means the cluster hasn't made any promise to the client. So, the contents in `ucp` need not be persistent and can be discarded directly.

Persistent `sp` and `last_exe`. restore the `sp` during recovery. The freshly elected leader will have the `sp`s from all nodes. The nodes check their own `last_as` and `last_exe`, if `last_as` < `last_exe`, Some commands might have completed the `fast_path` but haven't synced yet.

### New problom after the change

if `last_as` < `last_exe`, those commands might have executed on leader, but `fast_path` has not been completed. how should we handle this situation?

**Comment by rogercloud** [comment]
How could `last_as` be larger than `last_exe`? Every command is executed before syncing.

**Comment by themanforfree** [comment]
> 

Here should be `last_as` < `last_exe`, Fixed

**Comment by Phoenix500526** [comment]
> Assuming the successful completion of fast_round for cmd1. The leader executed cmd1 and wrote the log, yet synchronization has not commenced. If the cluster restarts at this time, sp will be lost. And the old leader will have an extra log entry, and cmd1 has successfully provided a response to the client.

Why should we address this problem within the context of cluster restart? Xline ensures data consistency only when the number of crashed nodes is fewer than the majority count. I think we can have a more in-depth discussion about this problem in issue #395, rather than here.

**Comment by themanforfree** [comment]
> > During cluster recovery, it is possible that a new leader might be elected, and this new leader can not restore ucp from the logs.
> 
> Why does this pose an issue? Whether in the fast path or the slow path, any command that doesn't complete its after_sync phase will be stored in the ucp. For commands in the fast path, the inability to restore the ucp won't be problematic since they can be recovered from the spec_pool on other nodes. As for commands in the slow path, it appears that we need not be concerned about them, as the cluster doesn't reach consensus on these commands.

Yes, I just mean that the recovery logic here is wrong, although we don't actually need it

**Comment by themanforfree** [comment]
> Why should we address this problem within the context of cluster restart? Xline ensures data consistency only when the number of crashed nodes is fewer than the majority count. I think we can have a more in-depth discussion about this problem in issue #395, rather than here.

That's what I thought at first. But now we need to safely shut down the entire cluster and restart it.
