### ISSUE TITLE
[Refactor]: Client retry timeout

### ISSUE THREAD

**Issue by bsbds** [xline-kv/Xline#474]
Currently in `ClientConfig` the default retry timeout is a fixed `50ms`
```rust
/// default retry timeout
#[must_use]
#[inline]
pub const fn default_retry_timeout() -> Duration {
    Duration::from_millis(50)
}
```
This sometimes too short and result in timeout failure in madsim CI tests (#473).

Maybe a better way to implement this retry is to use [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) algorithm.

**Comment by Phoenix500526** [comment]
Close in pr #479
