### ISSUE TITLE
Refactor BenchClient's implementation

### ISSUE THREAD

**Issue by Phoenix500526** [xline-kv/Xline#486]
Currently, for the `BenchClient` in Xline, we have the following implementation.
```Rust
/// Benchmark client
pub(crate) struct BenchClient {
    /// Name of the client
    name: String,
    /// etcd client
    etcd_client: EtcdClient,
    /// xline client
    xline_client: Client,
    /// Use xline client to send requests when true
    use_curp_client: bool,
}
```
As you can see, a `BenchClient` owns two different inner clients, one is `EtcdClient` while the other is `XlineClient`. Since both clients are part of a `BenchClient`, we have to construct them simultaneously. However, this is not an efficient way in that we only need one specific client in any specific bench test.  Therefore,  we need to refactor this implementation and use an enumeration to wrap these two clients as another data structure.

**Comment by Kikkon** [comment]
😇 Let me try.
