### ISSUE TITLE
[Bug]: cargo build show protoc error 

### ISSUE THREAD

**Issue by httaotao** [xline-kv/Xline#550]
### Description about the bug

when I used cargo build, it showed:

```
   Compiling toml v0.5.11
error: failed to run custom build command for `curp v0.1.0 (/home/hilton/Desktop/Xline/curp)`

Caused by:
  process didn't exit successfully: `/home/hilton/Desktop/Xline/target/debug/build/curp-c30ef72dcb272cb2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Failed to compile proto, error is Custom { kind: Other, error: "protoc failed: Could not make proto path relative: ./proto/common/src/curp-command.proto: No such file or directory\n" }', curp/build.rs:11:29
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```

rust version: ```rustc 1.70.0 (90c541806 2023-05-31) ```
protoc version: ```libprotoc 3.12.4 ```
os: ``` deepin v23```
kernel version: ``` 6.1.32-amd64-desktop-hwe```

### Version

0.6.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
The `curp-proto` is a submodule. Please use `git submodule update --init --recursive` to update the submodule and build again.

**Comment by httaotao** [comment]
> The `curp-proto` is a submodule. Please use `git submodule update --init --recursive` to update the submodule and build again.

that work, thanks

But it shows another error

```
Caused by:
  process didn't exit successfully: `/home/hilton/Desktop/Xline/target/debug/build/curp-c30ef72dcb272cb2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Failed to compile proto, error is Custom { kind: Other, error: "protoc failed: curp-command.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }', curp/build.rs:11:29
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `xlineapi v0.1.0 (/home/hilton/Desktop/Xline/xlineapi)
```

**Comment by Phoenix500526** [comment]
Xline requires protobuf-compiler >= 3.15. FYI: [quick_start.md](https://github.com/xline-kv/Xline/tree/master/doc/quick-start#ubuntudebian)

**Comment by iGxnon** [comment]
> We could set `--experimental_allow_proto3_optional` in build.rs. I’ll fix it in following pr

~~We could set `--experimental_allow_proto3_optional` in build.rs. I’ll fix it in following pr~~

Please update the protobuf-compiler version
