### ISSUE TITLE
[Bug]: Compilation failed

### ISSUE THREAD

**Issue by caicancai** [xline-kv/Xline#653]
### Description about the bug

![2024-02-16 10-44-18屏幕截图](https://github.com/xline-kv/Xline/assets/77189278/16e00ec4-bd58-4654-a3bb-5d2bfe4d0ce0)

### Version

0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iGxnon** [comment]
Use `git submodule update --init --recursive` if you cannot see any files in `crates/curp/proto`.

**Comment by caicancai** [comment]
> Use `git submodule update --init --recursive` if you cannot see any files in `crates/curp/proto/common`.

fail
![2024-02-18 23-09-46屏幕截图](https://github.com/xline-kv/Xline/assets/77189278/9cf1c148-ef61-4caa-95df-f91ec65d9320)

**Comment by caicancai** [comment]
I can see the file on crates/curp/proto/common

**Comment by iGxnon** [comment]
> I can see the file on crates/curp/proto/common

It seems that you should update your `protoc`
