### ISSUE TITLE
[Bug]: Quick Start README Change

### ISSUE THREAD

**Issue by ChaudharyRaman** [xline-kv/Xline#693]
### Description about the bug

While doing the local setup i found that in the Readme of quick start we have ,
`cp ./xline-test-utils/{private,public}.pem ./scripts`
instead it should be `cp ./fixtures/{private,public}.pem ./scripts`
![image](https://github.com/xline-kv/Xline/assets/97114586/ba68bc54-c762-4c0a-a7ec-2f4649a52a48)

### Version

0.1.0

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ChaudharyRaman** [comment]
@Phoenix500526  Please check. if correct, should i raise a PR for this one.

**Comment by Phoenix500526** [comment]
Yes, you're right. Please initiate a pr to fix it. Thanks for your contribution. @ChaudharyRaman

**Comment by Phoenix500526** [comment]
close in pr #694
