### ISSUE TITLE
[Feature]: Create a reusable gh workflow for build xline image

### ISSUE THREAD

**Issue by liangyuanpeng** [xline-kv/Xline#700]
### Description about the feature

Currently, there are multiple workflows that require building xline container images. It is worth creating a reusable workflow for building container images.

-  https://github.com/xline-kv/Xline/blob/75e51f4fcbb23b75d3b0f31ea69ed40684694f29/.github/workflows/benchmark.yml#L39
- https://github.com/xline-kv/Xline/blob/75e51f4fcbb23b75d3b0f31ea69ed40684694f29/.github/workflows/validation.yml#L42
- https://github.com/xline-kv/Xline/pull/696#discussion_r1527402223

Ideally, this reusable workflow will build the xline container image and upload the created image artifact through actions/upload-artifact.

Another option is to put the logic into a script and the user just needs to run a command like `make build-container` to build the container image.

The other things is the xline container image tag created in the current workflow is `latest`. I don't think this is a good idea. This is a real tag and in some scenarios it may be possible to pull the image from the repository instead of using the local.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChaudharyRaman** [comment]
Hi @liangyuanpeng  @Phoenix500526  Please assign it to me. I would like to work on workflows. Thank You.

**Comment by Phoenix500526** [comment]
Thanks for your contribution. @ChaudharyRaman

**Comment by liangyuanpeng** [comment]
@ChaudharyRaman Free feel to ask if you have any question here.

**Comment by ChaudharyRaman** [comment]
@liangyuanpeng sorry I was occupied with the college exam and writing a proposal for gsoc, will be raising a PR today for the issue.

**Comment by liangyuanpeng** [comment]
No worries, just according to your time to choice it.
