### ISSUE TITLE
[Feature]: A new release 0.6.2.

### ISSUE THREAD

**Issue by liangyuanpeng** [xline-kv/Xline#741]
### Description about the feature

IMO, it's worth to create a new release for https://github.com/xline-kv/Xline/pull/678, i think it's 0.6.2.

Would you like to release it?

@Phoenix500526 @bsbds 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liangyuanpeng** [comment]
/help 
(just test it)

**Comment by liangyuanpeng** [comment]
> https://github.com/xline-kv/Xline/actions/runs/8461486131/job/23181346641
> Error: User doesn't have enough access to the repo

**Comment by Phoenix500526** [comment]
The v0.7.0 is coming soon. We plan to release the new version in the next two weeks. Therefore, we don't have any plan to release v0.6.2.

**Comment by liangyuanpeng** [comment]
Make sense.
