### ISSUE TITLE
[Bug]: Implement ReadIndex

### ISSUE THREAD

**Issue by bsbds** [xline-kv/Xline#870]
### Description about the bug

When a network partition occurs, the leader in the smaller partition may not be aware that a new leader has already been elected in the cluster. If the original leader continues to serve read-only requests to clients during this time, it could result in stale reads. We should implement ReadIndex to enable read-only request on the leader.

### Version

0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Closed in PR #857
