### ISSUE TITLE
[refactor]: using expect instead of unwrap_or_else

### ISSUE THREAD

**Issue by lxl66566** [xline-kv/Xline#911]
currently the code uses a lot of `.unwrap_or_else(|| { unreachable!("...") });` / `.unwrap_or_else(|| { panic!("...") });`. I think it's better to use `exepct` because it's more intuitive, and using less code.

Things to do:
1. allow expect in clippy global rule
2. replace code

**Comment by bsbds** [comment]
We could also consider replacing
```rust
let Some(x) = y else {
    unreachable!("...");
};
 ```
with
```rust
let x  = y.expect("...");
```
