### ISSUE TITLE
[Bug]: cyclic deps

### ISSUE THREAD

**Issue by iGxnon** [xline-kv/Xline#927]
### Description about the bug

From rust-analyzer:

```
2024-07-30T04:14:30.078235Z ERROR cyclic deps: xline(Idx::<CrateData>(324)) -> xline_test_utils(Idx::<CrateData>(339)), alternative path: xline_test_utils(Idx::<CrateData>(339)) -> xline(Idx::<CrateData>(324))
```

It seems to have been avoided through `[dev-dependencies]`, but this is not a good solution since rust-analyzer reports it as an error.

Feasible solution: 

Extract the IT of Xline (which may include curp and client's IT) as a separate sub crate.

Or

Put xline-test-utils into xline and add `#[cfg(test)]` to its module:
```rust
// For test binary with `--features test` or test target
#[cfg(any(test, feature = "test"))]
#[cfg_attr(feature = "test", allow(unused))]
pub mod test_util;
```

### Version

0.6.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LucienY01** [comment]
Hi, I found a related issue in rust-analyzer repo #rust-lang/rust-analyzer/issues/14167, where the author indicated that we can safely ignore this error in our situation if everything works fine.

> It is not a wrong thing to do that, it's just r-a struggling with it (so yes, you are hitting this here). If everything works fine you can safely ignore the error.

**Comment by iGxnon** [comment]
Well, if it works, leave it as is. 🤣
