### ISSUE TITLE
[feature]: replace hardcoding "/tmp/xxx" path

### ISSUE THREAD

**Issue by lxl66566** [xline-kv/Xline#933]
currently we use many `/tmp/xxx` temp directory on db testing, and needs manually delete the dir in the end of test.
It's better to use some crate like [tempfile](https://crates.io/crates/tempfile) to help us.

pros: 
- no need to delete folders manually. programmers may forget to add remove code after testing.
- no need to worry about folder name collision. each test will always use different folder.
- although xline only supports test on linux, it's not bad to add some cross-platform ability.

things to do:
- add crate to `[dev-dependencies]` and replace `/tmp/xxx` path
- for those using `/tmp/xxx` path not in test mod, ex. [crates/xline/src/server/command.rs](https://github.com/xline-kv/Xline/blob/master/crates/xline/src/server/command.rs#L383), use [std::env::temp_dir](https://doc.rust-lang.org/std/env/fn.temp_dir.html) instead. 
    - for this ex. case, we need to define a function to generate snapshot path from uuid. It's not a good idea to use hardcoded string in coding.

**Comment by cswpy** [comment]
Hello there, I am new to the project and would love to contribute! I’d love to take a stab at this one.

**Comment by liangyuanpeng** [comment]
feel free to comment `/assignme` to assign it, and welcome :)

**Comment by cswpy** [comment]
Have been occupied by other stuff, will work on this later.

**Comment by JianMinTang** [comment]
Hi @lxl66566, I'm interested in contributing to this issue. Let me give it a try and work on solving it.

**Comment by lxl66566** [comment]
@JianMinTang Thank you for your enthusiasm! 
@cswpy Thank you for your previous dedication! Are you still planning to work on this issue?
