### ISSUE TITLE
[Bug]: Website Deploy/Install page leads to 404

### ISSUE THREAD

**Issue by shurup** [xline-kv/Xline#980]
### Description about the bug

Documentation on the project's website has a wrong link in the [Deploy / Install section](https://datenlord.github.io/xline-home/#/docs/Deploy). It leads to the [page](https://github.com/xline-kv/Xline/blob/master/doc/quick-start/README.md) which returns 404. I guess it should be [this page](https://github.com/xline-kv/Xline/blob/master/doc/QUICK_START.md) instead.

### Version

0.6.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bsbds** [comment]
Fixed in https://github.com/datenlord/xline-home/pull/5. Thanks!
